-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Proto2Sample_pb')


PROTO2SAMPLE = protobuf.Descriptor();
local PROTO2SAMPLE_NAME_FIELD = protobuf.FieldDescriptor();
local PROTO2SAMPLE_ID_FIELD = protobuf.FieldDescriptor();
local PROTO2SAMPLE_EMAIL_FIELD = protobuf.FieldDescriptor();

PROTO2SAMPLE_NAME_FIELD.name = "name"
PROTO2SAMPLE_NAME_FIELD.full_name = ".Proto2Sample.name"
PROTO2SAMPLE_NAME_FIELD.number = 1
PROTO2SAMPLE_NAME_FIELD.index = 0
PROTO2SAMPLE_NAME_FIELD.label = 2
PROTO2SAMPLE_NAME_FIELD.has_default_value = false
PROTO2SAMPLE_NAME_FIELD.default_value = ""
PROTO2SAMPLE_NAME_FIELD.type = 9
PROTO2SAMPLE_NAME_FIELD.cpp_type = 9

PROTO2SAMPLE_ID_FIELD.name = "id"
PROTO2SAMPLE_ID_FIELD.full_name = ".Proto2Sample.id"
PROTO2SAMPLE_ID_FIELD.number = 2
PROTO2SAMPLE_ID_FIELD.index = 1
PROTO2SAMPLE_ID_FIELD.label = 2
PROTO2SAMPLE_ID_FIELD.has_default_value = false
PROTO2SAMPLE_ID_FIELD.default_value = 0
PROTO2SAMPLE_ID_FIELD.type = 5
PROTO2SAMPLE_ID_FIELD.cpp_type = 1

PROTO2SAMPLE_EMAIL_FIELD.name = "email"
PROTO2SAMPLE_EMAIL_FIELD.full_name = ".Proto2Sample.email"
PROTO2SAMPLE_EMAIL_FIELD.number = 3
PROTO2SAMPLE_EMAIL_FIELD.index = 2
PROTO2SAMPLE_EMAIL_FIELD.label = 1
PROTO2SAMPLE_EMAIL_FIELD.has_default_value = false
PROTO2SAMPLE_EMAIL_FIELD.default_value = ""
PROTO2SAMPLE_EMAIL_FIELD.type = 9
PROTO2SAMPLE_EMAIL_FIELD.cpp_type = 9

PROTO2SAMPLE.name = "Proto2Sample"
PROTO2SAMPLE.full_name = ".Proto2Sample"
PROTO2SAMPLE.nested_types = {}
PROTO2SAMPLE.enum_types = {}
PROTO2SAMPLE.fields = {PROTO2SAMPLE_NAME_FIELD, PROTO2SAMPLE_ID_FIELD, PROTO2SAMPLE_EMAIL_FIELD}
PROTO2SAMPLE.is_extendable = false
PROTO2SAMPLE.extensions = {}

Proto2Sample = protobuf.Message(PROTO2SAMPLE)

